# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.daemon.performance.disable-logging=true
android.useAndroidX=true

# Performance Optimization
android.dependency.useConstraints=false

# Language and Style
kotlin.code.style=official

# R8/ProGuard settings
android.r8.strictFullModeForKeepRules=true
android.enableR8.fullMode=true
